/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
http://projecteuler.net/problem=2
*/
/*
Dört milyondan küçük bütün çift Fibonacci sayılarının toplamı nedir?…

Not: Fibonacci sayıları 1 ve 2 ile başlayıp sonraki sayı önceki iki terimin taoplamı şeklinde ilerleyen sayılardır (1,2,3,5,8,13,21,34,55,…).
http://fatihsultan.wordpress.com/2006/09/15/euler-projesi-1-2-3-soru/
*/
/*
real  0m0.002s
user	0m0.000s
sys	0m0.000s
*/
#include  <iostream>
#include  <vector>

using namespace std;

int main(){
	const unsigned int LIMIT = 4000000;
	unsigned int number1 = 1, number2 = 2, number3 = 0;
	unsigned int total = number2; //number2 = 2
	vector<unsigned int> vec;
	while(number3 < LIMIT){
		number3 = number1 + number2;
		number1 = number2;
		number2 = number3;

		if(number3 % 2 == 0)
			vec.push_back(number3);
	}
	
	for(int i=0; i<vec.size(); i++)
		total += vec[i];

	cout << "result: " << total << endl;
	return 0;
}
